### PR TITLE
Adding mdllog log package and also changing fabio code

### PR DESCRIPTION
**Pull request by avichalbadaya**
Includes a new package mdllog for logging which is a
wrapper on top of  go log package. Also made changes
in fabio code to include new package and enable log
level setting using config argument.

### CODE REVIEW

**Comment by magiconair** [comment]
First, let me thank you for the PR even though you've closed it. Generally, I prefer to start larger changes with a discussion as outlined in https://github.com/eBay/fabio/wiki/Contributing but I should make this more visible in the README, I guess. It is somewhat hidden at the bottom of the Wiki.

As for the change itself, the reason I didn't choose to use a leveled log package like glog or logrus is simplicity. The default log package and the level prefix are good enough for what fabio needs to do. Therefore, this is one less dependency to worry about. Also, log level filtering has the potential that people want to tune out excessive logging instead of finding the root cause. Issue #226 is such an example where investigating the excessive logging lead to the discovery of volatile health checks. 

Our production service which handles about 5.000 req/sec generates 15.000 log lines or 1 MB per day with most of the log messages about routes that don't exist. Once we address that, we should have about 100KB of logs per day. Therefore, IMHO fabio does not log much and if it does you should find out why and not suppress it. 

Frank

**Comment by magiconair** [comment]
Since this came up in #227 as well I think it could make sense to just log the delta instead of the full route table. I'm not a fan of log filtering for the reasons I've outlined. If the logging of the full routing table is your main concern then lets work on that. Also, if you want to do log filtering then there are easier ways to do this without the `mdllog` package which doesn't change code all over the place.

**Comment by avichalbadaya** [comment]
@magiconair : Yes, I am glad to hear that. If we can log just delta instead of full route table, it would certainly solve our issue with log volume. We wouldn't need log filtering in that case.

**Comment by killcity** [comment]
+1

**Comment by avichalbadaya** [comment]
Hi Frank,

Thanks much creating #238 . I also wanted to ask on point you mentioned about easier ways of log filtering. Can you share some details on what ideas you have to achieve it without much change in code ?

**Comment by magiconair** [comment]
I need to dig this up but I think the general approach is to put a filter writer in the log output stream which allows only strings with a certain prefix. Lets first see whether #238 fixes your problem.

**Pull request closed without merging**
