### PR TITLE
Issue #147: Support multiple metrics libraries

### PR DESCRIPTION
**Pull request by maier**
Add Circonus

### CODE REVIEW

**Comment by magiconair** [comment]
What happens when a service or an instance of a service appears and then disappears again? Will the circonus library stop reporting metrics for this instance? That's the reason behind the `Names()` and `Unregister()` functions since they allow fabio to trim the reported metrics to the current set of services and instances.

**Comment by maier** [comment]
Circonus doesn't keep a persistent set of metrics in memory (like gometrics does). The metrics are flushed after each submission. If a given metrics stops being used, it would no longer be sent to Circonus.

**Comment by magiconair** [comment]
OK. As for the vendored libraries: Updating `vendor.json` is not enough. You need to run `govendor add` for all libraries and check the source of the libraries in. I usually do this in a separate commit labeled 'Vendoring github.com/... plus dependencies' and then one additional commit with all the squashed changes for the issue. I can squash commits in github now but then I'd squash your changes and the vendored libs together. Could you please create two commits with first the vendored libs and then your changes? `git push -f` is fine.

**Comment by magiconair** [comment]
Check the last three commits on master for an example.

**Comment by maier** [comment]
ok. so what you want is:

commit vendor.json and all vendor source updates as "Vendoring github.com/circonus-labs/circonus-gometrics plus dependencies"

commit with just my changes to source tree

pull request

**Pull request closed without merging**
